server.port=8083
spring.application.name=notification-service

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
# 'earliest' means it will read messages even if they were sent before this service started
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# --- Tracing Configuration ---
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=health,info,tracing
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# --- Kafka Tracing (Critical for Consumers) ---
# This enables Micrometer to "see" the Kafka listener operations
spring.kafka.listener.observation-enabled=true