spring.application.name=discovery-server
server.port=8761

# These are mandatory to prevent the server from looking for itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false